import assert from "node:assert/strict";
import test from "node:test";
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repo = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function read(rel) {
  return readFileSync(resolve(repo, rel), "utf8");
}

test("sync-public-meta aligns version.json, site-config.js, and css cache", () => {
  execSync("node tools/scripts/sync-public-meta.mjs", { cwd: repo, stdio: "pipe" });
  const version = JSON.parse(read("apps/extension/manifest.json")).version;
  const published = JSON.parse(read("apps/web/public/version.json"));
  assert.equal(published.version, version);
  assert.match(read("apps/web/public/index.html"), new RegExp(`styles\\.css\\?v=${version}`));
  assert.match(read("apps/web/public/404.html"), new RegExp(`styles\\.css\\?v=${version}`));
  assert.match(read("apps/web/public/site-config.js"), /Generated by tools\/scripts\/sync-public-meta\.mjs/);
});
